name: Run Postman Collections

on:
  push:
    branches:
      - master

jobs:
  run-collections:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: ["collection1.json", "collection2.json", "collection3.json"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and Newman
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run ${{ matrix.collection }} -r json,json-summary,html \
            --reporter-json-export=reports/${{ matrix.collection }}-report.json \
            --reporter-html-export=reports/${{ matrix.collection }}-report.html
