name: Run Postman Collections

on:
  push:
    branches:
      - master

jobs:
  newman-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        collection-file:
          - "End-to-End Tests.postman_collection.json"
          - "Integration testing basics.postman_collection.json"
          - "REST API basics- CRUD, test & variable.postman_collection.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          mkdir -p reports
          COLLECTION_NAME="${{ matrix.collection-file }}"
          # Sanitize filename for report outputs (replace spaces, commas, dots)
          REPORT_NAME=$(echo "$COLLECTION_NAME" | sed -e 's|collections/||' -e 's/ /_/g' -e 's/,//g' -e 's/\./_/g')
          newman run "$COLLECTION_NAME" \
            -r json,json-summary,html \
            --reporter-json-export="reports/${REPORT_NAME}-report.json" \
            --reporter-html-export="reports/${REPORT_NAME}-report.html"

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports-${{ matrix.collection-file }}
          path: reports/
